# Generated by Django 3.0.5 on 2020-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100, null=True, verbose_name='Local do evento'),
        ),
    ]
